#!/usr/bin/env python3
"""Validate and package one completed Inspired V3 AWS run."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import zipfile
from pathlib import Path


WORKSPACE = Path(__file__).resolve().parents[4]
STUDENT_ROOT = WORKSPACE / "6ab10eb3b23ba_student_resource" / "student_resource"
TEST_DIR = STUDENT_ROOT / "dataset" / "test"
VALIDATOR = STUDENT_ROOT / "utils" / "validate_submission.py"
PACKAGE_ROOT = WORKSPACE / "code" / "business_entity_resolution" / "inspired_v3"
SHARED_VALIDATORS = WORKSPACE / "code" / "business_entity_resolution" / "aws"


def methodology(metrics: dict) -> str:
    thresholds = metrics.get("selected_thresholds", {})
    return f"""# Amazon ML Challenge 2026 — DevCore Inspired V3

**Team:** DevCore
**Member:** Pratik Daithankar

## Method

The pipeline performs country-partitioned, frequency-pruned inverted blocking in native-script and ASCII-transliterated views. Keys include normalized names and addresses, compact names, salient name-token pairs, name plus house number, address-token pairs, house number plus address anchor, postal plus house number, word tokens, and sampled character trigrams. Retrieval ranks candidate evidence and keeps at most {metrics['selected_cap_per_source']} candidates from each target source for every Source 1 entity. `candidate_pairs.tsv` is this pre-classifier candidate set. A CPU LightGBM model scores those pairs using candidate-only features; the final matching file applies validation-calibrated thresholds independently to Source 2 ({thresholds.get('S2', 'n/a')}) and Source 3 ({thresholds.get('S3', 'n/a')}) and assigns each target to at most one Source 1 entity.

## Validation and blocking results

Calibration-split macro F0.5 (used to select the operating point): **{metrics['validation_macro_f0_5']:.6f}**. Independent audit macro F0.5: **{metrics['independent_audit_macro_f0_5']:.6f}**. Audit candidate recall at the selected cap: **{metrics['independent_audit_candidate_recall']:.6f}**. Audit true positives: {metrics['independent_audit_pair_decisions']['true_positives']:,}; false positives: {metrics['independent_audit_pair_decisions']['false_positives']:,}; false negatives: {metrics['independent_audit_pair_decisions']['false_negatives']:,}; positive links missed by blocking: {metrics['independent_audit_pair_decisions']['missed_by_blocking']:,}.

The test blocking stage emitted {metrics['candidate_pairs']:,} pairs for {metrics['test_source1_rows']:,} Source 1 entities (mean {metrics['candidate_count_mean']:.3f}, p95 {metrics['candidate_count_p95']}, max {metrics['candidate_count_max']}). Estimated same-country search-space reduction: {metrics['candidate_reduction_ratio']:.3%}. AWS job runtime: {metrics['runtime_seconds'] / 3600:.2f} hours.

The audit entities were excluded from model fitting and threshold/cap selection. The audit F0.5 measures this independent training-data split and is not a guarantee of leaderboard performance. No external identity registries or labels were used.

## AWS implementation

Training, validation, candidate generation, and inference ran on AWS EC2 Spark. The included variant code and AWS CLI launcher are under `code/business_entity_resolution/inspired_v3/`. The archive includes the exact candidate and match TSVs generated by that run.
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--run-dir", type=Path, required=True,
                        help="Materialized output/inspired_v3/<run-id> directory")
    args = parser.parse_args()
    run_dir = args.run_dir.resolve()
    matching = run_dir / "matching_results.tsv"
    candidates = run_dir / "candidate_pairs.tsv"
    metrics_path = run_dir / "metrics.json"
    required_files = (matching, candidates, metrics_path)
    missing = [str(path) for path in required_files if not path.is_file()]
    if missing:
        raise FileNotFoundError("Missing completed AWS outputs: " + ", ".join(missing))

    metrics = json.loads(metrics_path.read_text(encoding="utf-8"))
    if metrics.get("smoke_test"):
        raise ValueError("Refusing to package smoke-test outputs as a challenge submission.")
    cap = int(metrics["selected_cap_per_source"])

    sys.path.insert(0, str(SHARED_VALIDATORS))
    from package_submission import validate_candidate_file

    subprocess.run(
        [sys.executable, str(VALIDATOR), "--matching", str(matching), "--test-dir", str(TEST_DIR)],
        cwd=run_dir, check=True,
    )
    validate_candidate_file(candidates, TEST_DIR / "test_source1.tsv", cap)

    archive_path = run_dir / f"DevCore_inspired_v3_{run_dir.name}.zip"
    documentation = methodology(metrics)
    with zipfile.ZipFile(archive_path, "w", compression=zipfile.ZIP_DEFLATED,
                         compresslevel=1) as archive:
        archive.write(matching, "output/matching_results.tsv")
        archive.write(candidates, "output/candidate_pairs.tsv")
        archive.write(metrics_path, "output/metrics.json")
        archive.writestr("Documentation_template.md", documentation)
        for path in sorted(PACKAGE_ROOT.rglob("*")):
            if (not path.is_file() or "__pycache__" in path.parts or path.suffix == ".pyc"):
                continue
            archive.write(path, Path("code/business_entity_resolution/inspired_v3")
                          / path.relative_to(PACKAGE_ROOT))

    with zipfile.ZipFile(archive_path) as archive:
        names = set(archive.namelist())
        expected = {
            "output/matching_results.tsv", "output/candidate_pairs.tsv",
            "output/metrics.json", "Documentation_template.md",
            "code/business_entity_resolution/inspired_v3/aws/run-inspired-v3.ps1",
        }
        if not expected.issubset(names):
            raise RuntimeError("Submission archive is missing required output or source files.")

    print(f"Created validated V3 submission: {archive_path}")
    audit_score = float(metrics["independent_audit_macro_f0_5"])
    print(f"Independent audit macro F0.5: {audit_score:.6f}")
    if audit_score < 0.95:
        print("The 0.95 target was not met; inspect validation errors before uploading.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
